// <auto-generated />
using Lab3_PRN231.Repository.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab3_PRN231.Repository.Migrations
{
    [DbContext(typeof(Lab3Prn231Context))]
    [Migration("20240926044449_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab3_PRN231.Repository.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("accountid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("password");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("account_pkey");

                    b.ToTable("account", (string)null);
                });

            modelBuilder.Entity("Lab3_PRN231.Repository.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoryid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("categoryname");

                    b.HasKey("Id")
                        .HasName("category_pkey");

                    b.ToTable("category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Beverages"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Condiments"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Confections"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dairy Products"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Grains/Cereals"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Meat/Poultry"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Produce"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Seafood"
                        });
                });

            modelBuilder.Entity("Lab3_PRN231.Repository.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("productid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("categoryid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("productname");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unitprice");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int")
                        .HasColumnName("unitsinstock");

                    b.HasKey("Id")
                        .HasName("product_pkey");

                    b.HasIndex("CategoryId");

                    b.ToTable("product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Chai",
                            UnitPrice = 18.00m,
                            UnitsInStock = 39
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Chang",
                            UnitPrice = 19.00m,
                            UnitsInStock = 17
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Name = "Aniseed Syrup",
                            UnitPrice = 10.00m,
                            UnitsInStock = 13
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Chef Anton's Cajun Seasoning",
                            UnitPrice = 22.00m,
                            UnitsInStock = 53
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Chef Anton's Gumbo Mix",
                            UnitPrice = 21.35m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Grandma's Boysenberry Spread",
                            UnitPrice = 25.00m,
                            UnitsInStock = 120
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 7,
                            Name = "Uncle Bob's Organic Dried Pears",
                            UnitPrice = 30.00m,
                            UnitsInStock = 15
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Name = "Northwoods Cranberry Sauce",
                            UnitPrice = 40.00m,
                            UnitsInStock = 6
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 6,
                            Name = "Mishi Kobe Niku",
                            UnitPrice = 97.00m,
                            UnitsInStock = 29
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 8,
                            Name = "Ikura",
                            UnitPrice = 31.00m,
                            UnitsInStock = 31
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Name = "Queso Cabrales",
                            UnitPrice = 21.00m,
                            UnitsInStock = 22
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "Queso Manchego La Pastora",
                            UnitPrice = 38.00m,
                            UnitsInStock = 86
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 8,
                            Name = "Konbu",
                            UnitPrice = 6.00m,
                            UnitsInStock = 24
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Name = "Tofu",
                            UnitPrice = 23.25m,
                            UnitsInStock = 35
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Name = "Genen Shouyu",
                            UnitPrice = 15.50m,
                            UnitsInStock = 39
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Name = "Pavlova",
                            UnitPrice = 17.45m,
                            UnitsInStock = 29
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Name = "Alice Mutton",
                            UnitPrice = 39.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 8,
                            Name = "Carnarvon Tigers",
                            UnitPrice = 62.50m,
                            UnitsInStock = 2
                        });
                });

            modelBuilder.Entity("Lab3_PRN231.Repository.Models.Product", b =>
                {
                    b.HasOne("Lab3_PRN231.Repository.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
