// <auto-generated />
using Lab1_PRN231.Repository.ProductDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab1_PRN231.Repository.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20240915041520_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab1_PRN231.Repository.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Beverages"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Condiments"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Confections"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Dairy Products"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Grains/Cereals"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Meat/Poultry"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Produce"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Seafood"
                        });
                });

            modelBuilder.Entity("Lab1_PRN231.Repository.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            ProductName = "Chai",
                            UnitPrice = 18.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            ProductName = "Chang",
                            UnitPrice = 19.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 2,
                            ProductName = "Aniseed Syrup",
                            UnitPrice = 10.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            ProductName = "Chef Anton's Cajun Seasoning",
                            UnitPrice = 22.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            ProductName = "Chef Anton's Gumbo Mix",
                            UnitPrice = 21.35m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            ProductName = "Grandma's Boysenberry Spread",
                            UnitPrice = 25.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 7,
                            ProductName = "Uncle Bob's Organic Dried Pears",
                            UnitPrice = 30.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            ProductName = "Northwoods Cranberry Sauce",
                            UnitPrice = 40.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 6,
                            ProductName = "Mishi Kobe Niku",
                            UnitPrice = 97.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 8,
                            ProductName = "Ikura",
                            UnitPrice = 31.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 4,
                            ProductName = "Queso Cabrales",
                            UnitPrice = 21.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 4,
                            ProductName = "Queso Manchego La Pastora",
                            UnitPrice = 38.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 8,
                            ProductName = "Konbu",
                            UnitPrice = 6.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 7,
                            ProductName = "Tofu",
                            UnitPrice = 23.25m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2,
                            ProductName = "Genen Shouyu",
                            UnitPrice = 15.50m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 3,
                            ProductName = "Pavlova",
                            UnitPrice = 17.45m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 6,
                            ProductName = "Alice Mutton",
                            UnitPrice = 39.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 8,
                            ProductName = "Carnarvon Tigers",
                            UnitPrice = 62.50m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 3,
                            ProductName = "Teatime Chocolate Biscuits",
                            UnitPrice = 9.20m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 3,
                            ProductName = "Sir Rodney's Marmalade",
                            UnitPrice = 81.00m,
                            UnitsInStock = 0
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 3,
                            ProductName = "Sir Rodney's Scones",
                            UnitPrice = 10.00m,
                            UnitsInStock = 0
                        });
                });

            modelBuilder.Entity("Lab1_PRN231.Repository.Entities.Product", b =>
                {
                    b.HasOne("Lab1_PRN231.Repository.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lab1_PRN231.Repository.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
